database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: app
  password: $ecureAppPass123
  url: jdbc:mysql://35.233.95.134:3306/workflowstreamer?autoReconnect=true&useSSL=false
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32

analyticsDomain: http://35.228.183.96

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 80

logging:
  level: INFO
  loggers:
    com.workflowstreamer: DEBUG